"""Reusable pipeline wrappers for the EEA 4.0/5.1 matrix comparison scripts.

This module intentionally does not reimplement the Excel business rules.  It
provides parameterized entry points that execute the existing script-level
business logic from a task working directory so legacy relative paths such as
``input/4.0`` and ``output`` continue to work for both CLI and Streamlit usage.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import importlib.util
import os
import runpy
import sys
from typing import Callable, Iterable

PROJECT_ROOT = Path(__file__).resolve().parents[1]

EXTRACT_SCRIPT = "01_extract_full_matrix_local_v13.py"
DEDUP_SCRIPT = "02_generate_dedup_signals_local_v13.py"
COMPARE_SCRIPT = "03_generate_compare_file5_local_v13.py"

FULL_40_FILE = "26R1 4.0全量信号矩阵清单.xlsx"
FULL_51_FILE = "26R2 5.1全量信号矩阵清单.xlsx"
DEDUP_40_FILE = "26R1 4.0全量信号-同名去重后.xlsx"
DEDUP_51_FILE = "26R2 5.1全量信号-同名去重后.xlsx"
COMPARE_FILE = "4.0和5.1同一信号差异点识别.xlsx"


@dataclass(frozen=True)
class PipelineResult:
    """Paths generated by a complete pipeline run."""

    input_40_dir: Path
    input_51_dir: Path
    output_dir: Path
    full_40_file: Path
    full_51_file: Path
    dedup_40_file: Path
    dedup_51_file: Path
    compare_file: Path


def _as_path(path: str | os.PathLike[str]) -> Path:
    return Path(path).expanduser().resolve()


def _ensure_project_importable() -> None:
    root = str(PROJECT_ROOT)
    if root not in sys.path:
        sys.path.insert(0, root)


def _script_path(script_name: str) -> Path:
    path = PROJECT_ROOT / script_name
    if not path.exists():
        raise FileNotFoundError(
            f"Required legacy script was not found: {path}. "
            "Keep the original business script in the repository root, or "
            "provide an importable implementation before running the pipeline."
        )
    return path


def _load_script_module(script_name: str):
    path = _script_path(script_name)
    module_name = f"_matrix_signal_legacy_{path.stem.replace('-', '_')}"
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load script module from {path}")
    module = importlib.util.module_from_spec(spec)
    _ensure_project_importable()
    spec.loader.exec_module(module)
    return module


def _first_callable(module: object, names: Iterable[str]) -> Callable[..., object] | None:
    for name in names:
        candidate = getattr(module, name, None)
        if callable(candidate):
            return candidate
    return None


def _call_if_available(script_name: str, function_names: Iterable[str], *args: Path) -> bool:
    module = _load_script_module(script_name)
    func = _first_callable(module, function_names)
    if func is None:
        return False
    func(*[str(arg) for arg in args])
    return True


def _run_script_in_workdir(script_name: str, work_dir: Path) -> None:
    """Run a legacy script with ``work_dir`` as CWD.

    Many historical scripts use relative paths like ``input/4.0`` and
    ``output``.  Running from the task directory preserves those expectations
    without changing sheet names, output field names, file names, or business
    rules.
    """

    script = _script_path(script_name)
    _ensure_project_importable()
    old_cwd = Path.cwd()
    try:
        os.chdir(work_dir)
        runpy.run_path(str(script), run_name="__main__")
    finally:
        os.chdir(old_cwd)


def _work_dir_for(input_40_dir: Path, input_51_dir: Path, output_dir: Path) -> Path:
    """Return the task root for the standard input/output layout."""

    candidates = [output_dir.parent, input_40_dir.parent.parent, input_51_dir.parent.parent]
    for candidate in candidates:
        if (candidate / "input" / "4.0") == input_40_dir and (candidate / "input" / "5.1") == input_51_dir:
            return candidate
    return output_dir.parent


def run_extract(
    input_40_dir: str | os.PathLike[str],
    input_51_dir: str | os.PathLike[str],
    output_dir: str | os.PathLike[str],
) -> tuple[Path, Path]:
    """Extract full 4.0 and 5.1 signal matrices into ``output_dir``."""

    input_40 = _as_path(input_40_dir)
    input_51 = _as_path(input_51_dir)
    output = _as_path(output_dir)
    input_40.mkdir(parents=True, exist_ok=True)
    input_51.mkdir(parents=True, exist_ok=True)
    output.mkdir(parents=True, exist_ok=True)

    if not _call_if_available(EXTRACT_SCRIPT, ("run_extract", "main"), input_40, input_51, output):
        _run_script_in_workdir(EXTRACT_SCRIPT, _work_dir_for(input_40, input_51, output))

    return output / FULL_40_FILE, output / FULL_51_FILE


def run_dedup(output_dir: str | os.PathLike[str]) -> tuple[Path, Path]:
    """Generate deduplicated 4.0 and 5.1 signal workbooks in ``output_dir``."""

    output = _as_path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    if not _call_if_available(DEDUP_SCRIPT, ("run_dedup", "main"), output):
        _run_script_in_workdir(DEDUP_SCRIPT, output.parent)

    return output / DEDUP_40_FILE, output / DEDUP_51_FILE


def run_compare(output_dir: str | os.PathLike[str]) -> Path:
    """Generate the final comparison workbook in ``output_dir``."""

    output = _as_path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    if not _call_if_available(COMPARE_SCRIPT, ("run_compare", "main"), output):
        _run_script_in_workdir(COMPARE_SCRIPT, output.parent)

    return output / COMPARE_FILE


def run_all(
    input_40_dir: str | os.PathLike[str],
    input_51_dir: str | os.PathLike[str],
    output_dir: str | os.PathLike[str],
) -> PipelineResult:
    """Run extract, deduplication, and comparison in order."""

    input_40 = _as_path(input_40_dir)
    input_51 = _as_path(input_51_dir)
    output = _as_path(output_dir)

    full_40, full_51 = run_extract(input_40, input_51, output)
    dedup_40, dedup_51 = run_dedup(output)
    compare = run_compare(output)

    return PipelineResult(
        input_40_dir=input_40,
        input_51_dir=input_51,
        output_dir=output,
        full_40_file=full_40,
        full_51_file=full_51,
        dedup_40_file=dedup_40,
        dedup_51_file=dedup_51,
        compare_file=compare,
    )
